### ISSUE TITLE
Consider requiring Hashable instead of Ord for the states

### ISSUE THREAD

**Issue by francisdb** [mazuschlag/haskov#5]
One of the issues I still have with the lib is that it enforces `Ord` on the states which I maybe would prefer to be `Hashable`. Not sure on this one though.

**Comment by mazuschlag** [comment]
Haskov uses Data.Map to construct its Markov chains, which requires Keys to be of `Ord`. To use Hashable we'd need to change the underlying data structure.

**Comment by francisdb** [comment]
You can close this one for my part, can always be reopened later when somebody really needs this
